/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrainTicket;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import javax.swing.ImageIcon;
/**
 *
 * This project is coded by Md shahajalal.
 * Bsc in CSE NWU,Khulna.
 */
public class TrainTicket extends javax.swing.JFrame implements ActionListener{
    /**
     * Creates new form TrainTicket
     */
    public TrainTicket() {
        setTitle("Train Ticketing System");
        ImageIcon icon=new ImageIcon("image/icon.jpg");
        setIconImage(icon.getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(6000, 6000));
        setPreferredSize(new java.awt.Dimension(14000, 9000));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Tax");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Sub  Total");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Total");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Total");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 68, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(13, 13, 13))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jRadioButton1.setText("First calss");

        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jRadioButton2.setText("Return");

        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jRadioButton3.setText("Economy");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Child");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Class");

        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jRadioButton4.setText("Standard");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jRadioButton5.setText("Single");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Destination");

        jRadioButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jRadioButton6.setText("Yes");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Adult");

        jRadioButton7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jRadioButton7.setText("Yes");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Ticket Type");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Chittagong", "Rajshahi", "Jaypurhat" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButton5)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addGap(112, 112, 112)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jRadioButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jRadioButton6)))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton4)
                                .addComponent(jRadioButton5))
                            .addComponent(jRadioButton6))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 96)); // NOI18N
        jLabel1.setText("Train Ticketing System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Ticket Type");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Adult");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Child");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Class");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("From");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("To");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Date");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Time");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Route");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("Ticket number");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setText("Price");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32))
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    FileWriter fileWriter;
    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.BLUE);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabel11.setText(null);
        jLabel12.setText(null);
        jLabel8.setText(null);
        jLabel33.setText(null);
        jLabel27.setText(null);
        jLabel8.setText(null);
        jLabel35.setText(null);
        jLabel21.setText(null);
        jLabel18.setText(null);
        jLabel19.setText(null);
        jLabel20.setText(null);
        jLabel31.setText(null);
        jLabel28.setText(null);
        jLabel26.setText(null);
        jLabel29.setText(null);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        double tax=17;
        double Milesk8=25.78;
        double Milesk12=25.10;
        double Milesk20=45.23;
        double Milesk30=55.98;
        double totalcost,eco=3.85,fclass=5.60;
                      //For starndard 
        if((jRadioButton4.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*Milesk8)/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk8 + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*(Milesk8 *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8 *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk8 + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
         else if((jRadioButton4.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*Milesk8)/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk8 + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*(Milesk8*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8 * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk8 + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
       else if((jRadioButton4.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*Milesk12)/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk12 + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*(Milesk12 *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12 *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk12 + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton4.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*Milesk12)/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk12 + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*(Milesk12*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12 * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk12 + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
         else if((jRadioButton4.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*Milesk20)/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk20 + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*(Milesk20 *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20 *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk20 + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton4.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*Milesk20)/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk20 + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*(Milesk20*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20 * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk20 + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
         else if((jRadioButton4.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*Milesk30)/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk30 + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*(Milesk30 *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30 *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk30 + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton4.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*Milesk30)/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk30 + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton4.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*(Milesk30*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30 * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk30 + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("STD");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
                  // For First class
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*(Milesk8+fclass))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk8 + fclass + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*((Milesk8+fclass) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",((Milesk8+fclass) *2));
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk8+fclass + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
         else if((jRadioButton1.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*(Milesk8+fclass))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk8+fclass + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*((Milesk8+fclass)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk8+fclass) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk8+fclass + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
       else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*(Milesk12+fclass))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk12+fclass + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*((Milesk12+fclass) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk12+fclass) *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk12+fclass + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton1.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*(Milesk12+fclass))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk12+fclass + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*((Milesk12+fclass)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk12+fclass) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk12+fclass + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
         else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*(Milesk20+fclass))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk20+fclass + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*((Milesk20+fclass) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk20+fclass) *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk20+fclass + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton1.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*(Milesk20+fclass))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk20+fclass + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*((Milesk20+fclass)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk20+fclass) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk20+fclass + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
         else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*(Milesk30+fclass))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk30+fclass + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*((Milesk30+fclass) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk30+fclass) *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk30+fclass + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton1.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*(Milesk30+fclass))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30+fclass);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk30+fclass + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton1.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*((Milesk30+fclass)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk30+fclass) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk30+fclass + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("FCLASS");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        } 
                 //For Economy    
        
             else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*(Milesk8+eco))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk8 + eco + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*((Milesk8+eco) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",((Milesk8+eco) *2));
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk8+eco + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
         else if((jRadioButton3.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*(Milesk8+eco))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk8+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk8+eco + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Dhaka"))
        {
            totalcost=(tax*((Milesk8+eco)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk8+eco) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk8+eco + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
       else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*(Milesk12+eco))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk12+eco + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*((Milesk12+eco) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk12+eco) *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk12+eco + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton3.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*(Milesk12+eco))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk12+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk12+eco + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
        {
            totalcost=(tax*((Milesk12+eco)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk12+eco) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk12+eco + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
         else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*(Milesk20+eco))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk20+eco + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*((Milesk20+eco) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk20+eco) *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk20+eco + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton3.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*(Milesk20+eco))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk20+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk20+eco + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rajshahi"))
        {
            totalcost=(tax*((Milesk20+eco)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk20+eco) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk20+eco + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
         else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*(Milesk30+eco))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk30+eco + totalcost);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE Way");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        } 
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*((Milesk30+eco) *2))/100;
            String sTax=String.format("$%.2f",totalcost);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30+eco *2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", (Milesk30+eco + totalcost) *2);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("ONE");
            jLabel20.setText("NIL");
        }
        else if((jRadioButton3.isSelected()) &&(jRadioButton5.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*(Milesk30+eco))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",Milesk30+eco);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", Milesk30+eco + totalcost-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("ONE WAY");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }
        else if((jRadioButton3.isSelected()) &&(jRadioButton2.isSelected()) && (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Jaypurhat"))
        {
            totalcost=(tax*((Milesk30+eco)*2))/100;
            String sTax=String.format("$%.2f",totalcost - 18);
            jLabel12.setText(sTax);
            String subTotal=String.format("$%.2f",(Milesk30+eco) * 2);
            jLabel11.setText(subTotal);
            String Total=String.format("$%.2f", ((Milesk30+eco + totalcost)*2)-18);
            jLabel35.setText(Total);
            jLabel8.setText(Total);
            jLabel18.setText("ECONOMY");
            jLabel21.setText("RETURN");
            jLabel19.setText("NILL");
            jLabel20.setText("ONE");
        }         
        
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  Calendar timer=Calendar.getInstance();
  timer.getTime();
  SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
  jLabel28.setText(tTime.format(timer.getTime()));
  SimpleDateFormat Tdate=new SimpleDateFormat("dd-MMM-yyyy");
  jLabel29.setText(Tdate.format(timer.getTime()));
  jLabel31.setText("Khulna ");
  jLabel26.setText((String)jComboBox1.getSelectedItem()+" ");
  int num1;
  String q1="";
  num1=1325+(int)(Math.random()*4238);
  q1+=num1+1325;
  jLabel33.setText(q1);
  jLabel27.setText("Any");
  jButton2.addActionListener(this);
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
